更新2024年年报
mtf-wiki/blog pull request #24
Opened 2024-12-31 15:05 UTC by ChisakaKanako

新年快乐

2024-12-31 16:33 UTC, Cryolitia requested changes
所有外部链接都需要web archive

2025-01-24 13:58 UTC, saeziae commented
麻煩再通讀一遍，咱在春節前合併。
各位辛苦了

2025-01-24 13:58 UTC, saeziae submitted a review, later dismissed

2025-01-24 14:00 UTC, ChisakaKanako commented
> 麻煩再通讀一遍，咱在春節前合併。 各位辛苦了

辛苦山前啦

2025-01-24 15:25 UTC, Cryolitia approved these changes

2025-01-24 16:30 UTC, saeziae approved these changes

2025-01-24 16:30 UTC, merged